language: python
sudo: required
python:
  - "2.7"
  - "3.4"
  - "3.5"
cache: pip
before_install:
# Update the pacakge repository
- sudo apt-get -qq update
# Install GMP (The GNU Multiple Precision Arithmetic Library)
- sudo apt-get install -y libgmp10 libgmp-dev libgmp3c2
# Install PBC (The Pairing-Based Cryptography Library)
- wget http://voltar.org/pbcfiles/libpbc0_0.5.12_amd64.deb
- wget http://voltar.org/pbcfiles/libpbc-dev_0.5.12_amd64.deb
- sudo dpkg -i libpbc0_0.5.12_amd64.deb
- sudo dpkg -i libpbc-dev_0.5.12_amd64.deb
# Install OpenSSL
- sudo apt-get install -y openssl libssl-dev
# Download charm
- git clone https://github.com/denniss17/charm.git
install:
# Install charm
- pip install -r charm/requirements.txt
- (cd ./charm && ./configure.sh)
- make -C ./charm
- make install -C ./charm
# Install other requirements
- pip install -r requirements.txt
script:
- mypy . -s --check-untyped-defs && nosetests --with-doctest